---
abstract: 'Profile memory usage of requests'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Carp: 0
  Catalyst: 0
  Catalyst::Controller: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  Test::WWW::Mechanize::Catalyst: 0
  parent: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101590'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-MemoryUsage
provides:
  Catalyst::Plugin::MemoryUsage:
    file: lib/Catalyst/Plugin/MemoryUsage.pm
    version: v0.3.1
requires:
  Devel::CheckOS: 0
  List::Util: 0
  MRO::Compat: 0
  Memory::Usage: 0
  Moose::Role: 0
  Number::Bytes::Human: 0
  Text::SimpleTable: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-MemoryUsage
  homepage: http://search.cpan.org/dist/Catalyst-Plugin-MemoryUsage/
  repository: git://github.com/yanick/Catalyst-Plugin-MemoryUsage.git
version: 0.3.1
x_authority: cpan:yanick
